# Generated by Django 3.2.8 on 2021-10-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
