# Generated by Django 3.2.8 on 2021-10-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
